FileVersion = 1
Projects = {ClockWorkEditor = {Path = "ClockWorkEditor"}, ClockWorkEngine = {Path = "ClockWorkEngine"}, wgpu-Beef = {Path = "lib/wgpu-Beef"}, SDL3 = {Path = "lib/SDL3-Beef"}, TailTrace = {Path = "lib/TailTrace"}, corlib = "*"}

[Workspace]
StartupProject = "ClockWorkEditor"

[Configs.Test.Win32]
ConfigSelections = {ClockWorkEditor = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {ClockWorkEditor = {Config = "Debug"}}
