FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["ClockWorkEngine\\src\\Window\\CWindow.bf", "ClockWorkEngine\\src\\Application\\CApplication.bf", "ClockWorkEngine\\src\\ClockWorkCore\\Worker\\CWorkerThread.bf", "ClockWorkEditor\\src\\EditorApplication\\CEditorApplication.bf", "ClockWorkEngine\\src\\ClockWorkCore\\CoreMinimal.bf", "ClockWorkEngine\\src\\ClockWorkEngine.bf", "ClockWorkEngine\\src\\Interfaces\\ICWLogger.bf", "ClockWorkEngine\\src\\ClockWorkCore\\Module\\Modules\\CLogger.bf", "ClockWorkEngine\\src\\Entry.bf", "Disassembly", "lib\\TailTrace\\src\\Formatting\\DefaultFormatter.bf", "ClockWorkEngine\\src\\ClockWorkCore\\ClockWorkUI\\Window\\CWindow.bf", "ClockWorkEditor\\src\\PanelManager\\Panel\\Panels\\CToolBarPanel.bf", "ClockWorkEditor\\src\\PanelManager\\Panel\\CPanel.bf", "ClockWorkEditor\\src\\PanelManager\\CPanelManager.bf", "ClockWorkEditor\\src\\Window\\WindowRenderer\\Renderers\\CPrimaryWindowRenderer.bf", "ClockWorkEditor\\src\\Window\\Gui\\Guis\\CPrimaryGui.bf", "ClockWorkEngine\\src\\Core\\ModuleManager\\Module\\Modules\\CTypeRegister.bf", "ClockWorkEngine\\src\\Core\\ModuleManager\\Module\\CModule.bf"]

[MainWindow]
X = 0
Y = 0
Width = 1936
Height = 1100
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 272.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "CWindow.bf"
TabWidth = 110.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ClockWorkEngine\\src\\Window\\CWindow.bf"
CursorPos = 304
VertPos = 90.0
ProjectName = "ClockWorkEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CApplication.bf"
TabWidth = 128.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ClockWorkEngine\\src\\Application\\CApplication.bf"
CursorPos = 126
ProjectName = "ClockWorkEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CWorkerThread.bf"
TabWidth = 137.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ClockWorkEngine\\src\\ClockWorkCore\\Worker\\CWorkerThread.bf"
CursorPos = 106
ProjectName = "ClockWorkEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ClockWorkEngine.bf"
TabWidth = 146.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ClockWorkEngine\\src\\ClockWorkEngine.bf"
CursorPos = 1153
ProjectName = "ClockWorkEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entry.bf"
TabWidth = 74.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ClockWorkEngine\\src\\Entry.bf"
CursorPos = 42
ProjectName = "ClockWorkEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CEditorApplication.bf"
TabWidth = 153.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ClockWorkEditor\\src\\EditorApplication\\CEditorApplication.bf"
CursorPos = 648
VertPos = 180.0
ProjectName = "ClockWorkEditor"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ICWLogger.bf"
TabWidth = 109.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ClockWorkEngine\\src\\Interfaces\\ICWLogger.bf"
CursorPos = 357
ProjectName = "ClockWorkEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CoreMinimal.bf"
TabWidth = 119.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ClockWorkEngine\\src\\ClockWorkCore\\CoreMinimal.bf"
CursorPos = 177
ProjectName = "ClockWorkEngine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CLogger.bf"
TabWidth = 94.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "ClockWorkEngine\\src\\ClockWorkCore\\Module\\Modules\\CLogger.bf"
CursorPos = 1446
ProjectName = "ClockWorkEngine"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 306.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.2413973
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Memory"
TabWidth = 99.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.0
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.7586027
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
