FileVersion = 1
Projects = {ClockWorkEditor = {Path = "ClockWorkEditor"}, ClockWorkEngine = {Path = "ClockWorkEngine"}, corlib = "*", "SDL3-Beef.git" = {Git = "https://github.com/Booklordofthedings/SDL3-Beef.git"}, "TailTrace.git" = {Git = "https://github.com/RogueMacro/TailTrace.git"}, ImGuiImplSDL = "*", ImGui = "*"}

[Workspace]
StartupProject = "ClockWorkEditor"

[Configs.Test.Win32]
ConfigSelections = {ClockWorkEditor = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {ClockWorkEditor = {Config = "Debug"}}
