FileVersion = 1

[Workspace]
StartupProject = "ClockWorkEditor"

[Projects]
ClockWorkEditor = {Path = "ClockWorkEditor"}
ClockWorkEngine = {Path = "ClockWorkEngine"}
wgpu-Beef = {Path = "lib/wgpu-Beef"}
SDL3 = {Path = "lib/SDL3-Beef"}

[Configs.Test.Win32]
ConfigSelections = {ClockWorkEditor = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {ClockWorkEditor = {Config = "Debug"}}
