FileVersion = 1
Dependencies = {corlib = "*", "SDL3-Beef.git" = {Git = "https://github.com/Booklordofthedings/SDL3-Beef.git"}, "TailTrace.git" = {Git = "https://github.com/RogueMacro/TailTrace.git"}}

[Project]
Name = "ClockWorkEngine"
TargetType = "BeefLib"
StartupObject = "ClockWorkEngine.Program"
