FileVersion = 1
Dependencies = {corlib = "*", ClockWorkEngine = "*", wgpu-Beef = "*", SDL3 = "*", TailTrace = "*"}

[Project]
Name = "ClockWorkEditor"
StartupObject = "ClockWorkEditor.ClockWorkEditor"
